// app/chrome-extension/entrypoints/sidepanel/components/agent-chat/AgentTimeline.tsx
import type { AgentThreadState, TimelineItem } from '../../composables/useAgentThreads';
import AgentTimelineItem from './AgentTimelineItem';

type AgentTimelineProps = {
  items: TimelineItem[];
  state: AgentThreadState;
  serverPort?: number | null;
};

export default function AgentTimeline({ items, state: _state, serverPort }: AgentTimelineProps) {
  return (
    <div className="pl-1 space-y-3">
      <div className="relative pl-5 space-y-4 ml-1">
        {items.map((item, index) => (
          <AgentTimelineItem
            key={item.id}
            item={item}
            isLast={index === items.length - 1}
            serverPort={serverPort}
          />
        ))}
      </div>
    </div>
  );
}

// chrome-mcp-react/app/chrome-extension/entrypoints/sidepanel/components/agent-chat/AgentTimeline.vue
<template>
  <ReactComponentHost :component="AgentTimelineReact" :component-props="componentProps" />
</template>

<script lang="ts" setup>
import { computed, inject, ref } from 'vue';
import type { AgentThreadState, TimelineItem } from '../../composables/useAgentThreads';
import { AGENT_SERVER_PORT_KEY } from '../../composables';
import ReactComponentHost from '@/entrypoints/shared/vue/ReactComponentHost.vue';
import AgentTimelineReact from './AgentTimeline';

const props = defineProps<{
  items: TimelineItem[];
  state: AgentThreadState;
}>();

const injectedServerPort = inject(AGENT_SERVER_PORT_KEY, ref<number | null>(null));

const componentProps = computed(() => ({
  items: props.items,
  state: props.state,
  serverPort: injectedServerPort.value,
}));
</script>
